### ISSUE TITLE
Fixing relations -- 3.2

### ISSUE THREAD

**Issue by akrzemi1** [tomaszkam/proposals#34]
Sugeruję zastąpić sekcję 3.2 tym: http://htmlpreview.github.io/?https://github.com/akrzemi1/__sandbox__/blob/master/__MAIN__relations.html

**Comment by tomaszkam** [comment]
Nie do końca się z tym zgadzam, bo dalej monco sugerujesz że
CommonReference jest jakoś potrzebny do matematycznego zdefiniowania weak
relacji, a to nie jest kompletnie prawda - argumenty Michała z discorda
kompletnie mnie nie przekonują.

Ja wolę skupić się na tym, że CommonReference jest dziełem twórców Range TS
i wcale nie jest potrzebny.

wt., 25 wrz 2018, 14:15 użytkownik Andrzej Krzemieński <
notifications@github.com> napisał:

**Comment by tomaszkam** [comment]
Inaczej mówiąc to co piszesz w akapicie drugim, a potrzebie istnienia
wspólnego typu nie jest prawdą.

wt., 25 wrz 2018, 14:41 użytkownik Tomasz Kamiński <tomaszkam@gmail.com>
napisał:

**Comment by akrzemi1** [comment]
Ja nie wiem, czy formalnie istnienie tego typu jest potrzebne czy nie, czy nie wystarczy tylko ileś równań i ich zachowanie; ale we wszystkich przykładach, które do tej pory zostały zaprezentowane w tym sporze dostrzegam wyraźnie taki wspólny typ. N.p. jak mówimy, że posortujemy *po czasach odlotów legów* albo te *itiny, gdzie czasy odlotów legów są leksykograficznie większe niż para dat D1 D2*, to ewidentnie implikuje abstrakcyjny twór "sekwencja dat". 

Stwierdzenie "CommonReference jest dziełem twórców Range TS i wcale nie jest potrzebny" może i jest prawdziwe (ale udowadnianie takiego typu twierdzeń jest trudne) ale też bardzo konfrontacyjne. Proponowałbym ujęcie problemu takie, które pozwoli osiągnąć ten sam cel, a zarazem ułatwi zbudowanie konsensusu.

**Comment by akrzemi1** [comment]
Druga wersja: http://htmlpreview.github.io/?https://raw.githubusercontent.com/akrzemi1/__sandbox__/master/__MAIN__relations.html

**Comment by akrzemi1** [comment]
Trzecia wersja: http://htmlpreview.github.io/?https://github.com/akrzemi1/__sandbox__/blob/master/__MAIN__relations.html
